CREATE TABLE PUBLIC."SECTION" (
	ID INTEGER NOT NULL,
	PARENT_ID INTEGER,
	DESCRIPTION VARCHAR(100),
	URL VARCHAR(200),
	CONSTRAINT SECTION_PK PRIMARY KEY (ID),
	CONSTRAINT SECTION_SECTION_FK FOREIGN KEY (PARENT_ID) REFERENCES PUBLIC."SECTION"(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.ITEM_MASTER (
	ID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(100),
	JSON CLOB,
	SECTION_ID INTEGER,
	CONSTRAINT ITEM_MASTER_PK PRIMARY KEY (ID),
	CONSTRAINT ITEM_MASTER_SECTION_FK FOREIGN KEY (SECTION_ID) REFERENCES PUBLIC."SECTION"(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX ITEM_MASTER_SECTION_FK_INDEX_F ON PUBLIC.ITEM_MASTER (SECTION_ID);

CREATE INDEX PRIMARY_KEY_2E ON PUBLIC.ITEM_MASTER (ID);


CREATE TABLE PUBLIC.ITEM (
	ID INTEGER NOT NULL,
	"VALUE" DOUBLE,
	DATE TIMESTAMP NOT NULL,
	CONSTRAINT ITEMS_PK PRIMARY KEY (ID,DATE),
	CONSTRAINT ITEMS_ITEM_MASTER_FK FOREIGN KEY (ID) REFERENCES PUBLIC.ITEM_MASTER(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX ITEMS_ITEM_MASTER_FK_INDEX_4 ON PUBLIC.ITEM (ID);

CREATE INDEX PRIMARY_KEY_4 ON PUBLIC.ITEM (ID,DATE);
